main: io.jcurtis.telefee.TeleFee
version: 1.0
name: TeleFee
commands:
  telefee:
    description: TeleFee command
    usage: /<command>
    aliases: [tpf, tfee]
  tpaccept:
    description: TeleFee accept command
    usage: /<command>
    aliases: [tpa]